/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'
import { Route as SitesSiteIdInvitationsRouteImport } from './routes/sites.$siteId.invitations'
import { Route as SitesSiteIdMessagesRouteImport } from './routes/sites.$siteId.messages'
import { Route as SitesSiteIdSettingsRouteImport } from './routes/sites.$siteId.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdInvitationsRoute = SitesSiteIdInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => SitesSiteIdRoute,
} as any)
const SitesSiteIdMessagesRoute = SitesSiteIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => SitesSiteIdRoute,
} as any)
const SitesSiteIdSettingsRoute = SitesSiteIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SitesSiteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/handoff': typeof HandoffRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/api/$': typeof ApiSplatRoute
  '/sites/$siteId': typeof SitesSiteIdRouteWithChildren
  '/sites/$siteId/invitations': typeof SitesSiteIdInvitationsRoute
  '/sites/$siteId/messages': typeof SitesSiteIdMessagesRoute
  '/sites/$siteId/settings': typeof SitesSiteIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/handoff': typeof HandoffRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/api/$': typeof ApiSplatRoute
  '/sites/$siteId': typeof SitesSiteIdRouteWithChildren
  '/sites/$siteId/invitations': typeof SitesSiteIdInvitationsRoute
  '/sites/$siteId/messages': typeof SitesSiteIdMessagesRoute
  '/sites/$siteId/settings': typeof SitesSiteIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/handoff': typeof HandoffRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/api/$': typeof ApiSplatRoute
  '/sites/$siteId': typeof SitesSiteIdRouteWithChildren
  '/sites/$siteId/invitations': typeof SitesSiteIdInvitationsRoute
  '/sites/$siteId/messages': typeof SitesSiteIdMessagesRoute
  '/sites/$siteId/settings': typeof SitesSiteIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/handoff'
    | '/login'
    | '/recover'
    | '/api/$'
    | '/sites/$siteId'
    | '/sites/$siteId/invitations'
    | '/sites/$siteId/messages'
    | '/sites/$siteId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/handoff'
    | '/login'
    | '/recover'
    | '/api/$'
    | '/sites/$siteId'
    | '/sites/$siteId/invitations'
    | '/sites/$siteId/messages'
    | '/sites/$siteId/settings'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/handoff'
    | '/login'
    | '/recover'
    | '/api/$'
    | '/sites/$siteId'
    | '/sites/$siteId/invitations'
    | '/sites/$siteId/messages'
    | '/sites/$siteId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  HandoffRoute: typeof HandoffRoute
  LoginRoute: typeof LoginRoute
  RecoverRoute: typeof RecoverRoute
  ApiSplatRoute: typeof ApiSplatRoute
  SitesSiteIdRoute: typeof SitesSiteIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId/invitations': {
      id: '/sites/$siteId/invitations'
      path: '/invitations'
      fullPath: '/sites/$siteId/invitations'
      preLoaderRoute: typeof SitesSiteIdInvitationsRouteImport
      parentRoute: typeof SitesSiteIdRoute
    }
    '/sites/$siteId/messages': {
      id: '/sites/$siteId/messages'
      path: '/messages'
      fullPath: '/sites/$siteId/messages'
      preLoaderRoute: typeof SitesSiteIdMessagesRouteImport
      parentRoute: typeof SitesSiteIdRoute
    }
    '/sites/$siteId/settings': {
      id: '/sites/$siteId/settings'
      path: '/settings'
      fullPath: '/sites/$siteId/settings'
      preLoaderRoute: typeof SitesSiteIdSettingsRouteImport
      parentRoute: typeof SitesSiteIdRoute
    }
  }
}

interface SitesSiteIdRouteChildren {
  SitesSiteIdInvitationsRoute: typeof SitesSiteIdInvitationsRoute
  SitesSiteIdMessagesRoute: typeof SitesSiteIdMessagesRoute
  SitesSiteIdSettingsRoute: typeof SitesSiteIdSettingsRoute
}

const SitesSiteIdRouteChildren: SitesSiteIdRouteChildren = {
  SitesSiteIdInvitationsRoute: SitesSiteIdInvitationsRoute,
  SitesSiteIdMessagesRoute: SitesSiteIdMessagesRoute,
  SitesSiteIdSettingsRoute: SitesSiteIdSettingsRoute,
}

const SitesSiteIdRouteWithChildren = SitesSiteIdRoute._addFileChildren(
  SitesSiteIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  HandoffRoute: HandoffRoute,
  LoginRoute: LoginRoute,
  RecoverRoute: RecoverRoute,
  ApiSplatRoute: ApiSplatRoute,
  SitesSiteIdRoute: SitesSiteIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
